export type BlogSeverity = "Major" | "Significant" | "Notable"

export type BlogSource = {
  label: string
  page: number
}

export type BlogFlag = {
  severity: BlogSeverity
  title: string
  body: string
  sources: BlogSource[]
}

export type BlogSection = {
  id: string
  label: string
  icon: string
  flags: BlogFlag[]
}

export type BlogPost = {
  slug: string
  title: string
  date: string
  summary: string
  overview: string[]
  sourceNote: string
  sections: BlogSection[]
}

export const SOURCE_PDF_URL =
  "https://drive.google.com/file/d/1l_eob7qCMQRR7VDnRXTA54Q2AigWsTc5/view?usp=drive_link"

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "bam-franchising-2026-fdd",
    title: "BAM Franchising, Inc. - 2026 FDD",
    date: "June 2026",
    summary:
      "A review of Brick's and Minifigs 2026 Franchise Disclosure Document. Generated by Claude + Gemini. I've personally (human) reviewed the cited items, but mistakes can still happen. After I have time to read through the entire 393 page document, I'll write a personal review. ",
    overview: [
      "The most serious issue is the FDD's own Special Risks disclosure: BAM's financial condition \"calls into question the franchisor's financial ability to provide services and support you.\" That is not an outside analyst's opinion; it is BAM's own mandatory disclosure. The negative equity position, now at ($621K) and worsening every year, is the root cause.",
      "The trademark position is alarming for a 224-location franchise system. \"Bricks & Minifigs\" only has supplemental register protection, which is weaker than principal register protection. Principal register applications were filed in July 2023 and are still pending more than three years later, leaving the brand's IP protection exposed.",
      "The pipeline of 70 signed-but-unopened stores is also a significant contingent liability. It represents about $2.55M in deferred revenue that must either be earned through successful openings or potentially refunded if those stores do not open.",
    ],
    sourceNote: "",
    sections: [
      {
        id: "critical",
        label: "Major",
        icon: "AlertTriangle",
        flags: [
          {
            severity: "Major",
            title: "BAM's own FDD questions its financial ability to support franchisees",
            body:
              'The Special Risks section explicitly states that the franchisor\'s financial condition "calls into question" its ability to provide services and support. This is a mandatory disclosure and directly reinforces the balance-sheet concern in the audited financials.',
            sources: [
              { label: "Special Risks (p. 5)", page: 5 },
              { label: "Item 21 (p. 76)", page: 76 },
            ],
          },
          {
            severity: "Major",
            title: "Primary trademark is not on the principal register",
            body:
              '"Bricks & Minifigs" has been on the supplemental register since 2012. The FDD says supplemental registration provides more limited protections and that a challenged user may be forced to switch brands. Principal-register applications were filed in July 2023 and remain pending.',
            sources: [
              { label: "Special Risks (p. 5)", page: 5 },
              { label: "Item 13 - Trademarks (p. 48-49)", page: 48 },
            ],
          },
          {
            severity: "Major",
            title: "Negative stockholders' equity - ($621K)",
            body:
              "Total liabilities of $6.69M exceed total assets of $6.07M. The deficit worsened from ($182K) in 2022 to ($621K) in 2025, and the company has not shown positive equity in the history presented.",
            sources: [{ label: "Item 21 - Balance Sheet (p. 76)", page: 76 }],
          },
          {
            severity: "Major",
            title: "70 signed franchise agreements with stores not yet open",
            body:
              "As of Dec. 31, 2025, 70 franchise agreements had been signed but not yet opened, with 83 projected new locations in 2026. The FDD flags this as a special risk and the deferred franchise revenue on the balance sheet magnifies the refund-risk if openings do not happen.",
            sources: [
              { label: "Special Risks (p. 5)", page: 5 },
              { label: "Item 20 - Table 5 (p. 74)", page: 74 },
              { label: "Item 21 (p. 76)", page: 76 },
            ],
          },
        ],
      },
      {
        id: "significant",
        label: "Significant",
        icon: "AlertCircle",
        flags: [
          {
            severity: "Significant",
            title: "Mandatory minimum royalties regardless of sales",
            body:
              "Royalties are 6% of gross revenue or $500 per month minimum, whichever is greater. The brand fund adds 1%, local marketing requires 3%, and a technology fund of up to 1% may be added. The FDD warns that inability to make the payments may result in termination.",
            sources: [
              { label: "Special Risks #2 (p. 5)", page: 5 },
              { label: "Item 6 - Other Fees (p. 15)", page: 15 },
            ],
          },
          {
            severity: "Significant",
            title: "All disputes must be resolved in Utah",
            body:
              "Arbitration, mediation, and litigation are all required in Utah County, Utah under Utah law. For out-of-state buyers, that can raise the cost of any dispute and may reduce leverage in settlement discussions.",
            sources: [
              { label: "Special Risks #1 (p. 5)", page: 5 },
              { label: "Item 17(u)-(v) (p. 58)", page: 58 },
            ],
          },
          {
            severity: "Significant",
            title: "3-year post-termination non-compete",
            body:
              "After the franchise ends, a former franchisee cannot compete within 25 miles of any company-owned or franchised location for 3 years. The agreement also restricts online e-commerce activity anywhere in the world for 3 years.",
            sources: [{ label: "Item 17(r) (p. 58)", page: 58 }],
          },
          {
            severity: "Significant",
            title: "Transfer fee jumped from $5,000 to $30,000",
            body:
              "The transfer fee cited in earlier materials was $5,000. The 2026 FDD lists a $30,000 transfer fee, plus a mandatory $10,000 training fee for the transferee and possible broker referral costs.",
            sources: [
              { label: "Item 5 - Transfer Fee (p. 14)", page: 14 },
              { label: "Item 6 - Transfer Fee table (p. 15)", page: 15 },
              { label: "Item 17(n) (p. 58)", page: 58 },
            ],
          },
          {
            severity: "Significant",
            title: "Total initial investment increased sharply",
            body:
              "Earlier materials listed an investment range of $108,500 to $276,400. The 2026 FDD now discloses $303,500 to $597,500, more than doubling the high end and materially changing the capital required to enter the system.",
            sources: [{ label: "Item 7 - Initial Investment (p. 20-21)", page: 20 }],
          },
          {
            severity: "Significant",
            title: "Some former franchisees are bound by NDAs",
            body:
              "The FDD says some former franchisees signed mutual termination and release agreements that prohibit disparagement. That does not block diligence entirely, but it can reduce the candor of reference conversations.",
            sources: [
              { label: "Item 20 - Table 3 (p. 70-73)", page: 70 },
              { label: "Item 20 - Exhibit G disclosure (p. 75)", page: 75 },
            ],
          },
        ],
      },
      {
        id: "notable",
        label: "Notable",
        icon: "Info",
        flags: [
          {
            severity: "Notable",
            title: "Bottom quartile stores average only $293K revenue",
            body:
              "The 4th quartile of 39 stores averaged $293,524 in 2025 revenue. With royalties, marketing, occupancy, staffing, and COGS, that level of revenue looks tight and may sit near breakeven or below it.",
            sources: [{ label: "Item 19 - Table 2 (p. 62)", page: 62 }],
          },
          {
            severity: "Notable",
            title: "Gross margin data is incomplete",
            body:
              "Item 19 gross margin tables cover only 104 of 153 qualifying stores because some locations did not report reliably. That leaves buyers with an incomplete profitability picture.",
            sources: [{ label: "Item 19 - Tables 3-4 (p. 62-63)", page: 62 }],
          },
          {
            severity: "Notable",
            title: "Washington AG action over no-poach clauses",
            body:
              "BAM entered into an Assurance of Discontinuance in 2019 over franchise no-poach provisions. The matter was resolved, but it still signals an earlier governance issue worth noting.",
            sources: [{ label: "Item 3 - Litigation (p. 13)", page: 13 }],
          },
          {
            severity: "Notable",
            title: "Franchisor is not contractually required to defend trademarks",
            body:
              "Item 13 says BAM is not obligated under the franchise agreement to protect marks or defend franchisees against infringement claims. The company says it intends to do so as a matter of policy, but that is discretionary.",
            sources: [{ label: "Item 13 - Trademarks (p. 50)", page: 50 }],
          },
        ],
      },
    ],
  },
]
